name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zsh
      run: sudo apt-get install -y zsh

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install make
      run: sudo apt-get install -y make

    - name: Run Make CI
      run: zsh -c "make ci"
